<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:h2:file:./data/audio-editor-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

server:
  port: 8080

# ðŸ—‚ï¸ Ð¨Ð»ÑÑ…Ð¸ Ð´Ð¾ Ð´Ð¸Ñ€ÐµÐºÑ‚Ð¾Ñ€Ñ–Ð¹ Ð·Ð±ÐµÑ€Ñ–Ð³Ð°Ð½Ð½Ñ
storage:
  root: ${user.dir}/storage
  uploadsDir: ${user.dir}/storage/uploads
  exportsDir: ${user.dir}/storage/exports
  wavDir: ${user.dir}/storage/wav

# âš™ï¸ Ð¨Ð»ÑÑ… Ð´Ð¾ ffmpeg (ÑÐºÑ‰Ð¾ Ð² PATH, Ð¿Ñ€Ð¾ÑÑ‚Ð¾ Ð»Ð¸Ñˆ ffmpeg)
ffmpeg:
  path: ffmpeg
=======
spring:
  datasource:
    url: jdbc:h2:file:./data/audio-editor-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

server:
  port: 8080

# ðŸ—‚ï¸ Ð¨Ð»ÑÑ…Ð¸ Ð´Ð¾ Ð´Ð¸Ñ€ÐµÐºÑ‚Ð¾Ñ€Ñ–Ð¹ Ð·Ð±ÐµÑ€Ñ–Ð³Ð°Ð½Ð½Ñ
storage:
  root: ${user.dir}/storage
  uploadsDir: ${user.dir}/storage/uploads
  exportsDir: ${user.dir}/storage/exports
  wavDir: ${user.dir}/storage/wav

# âš™ï¸ Ð¨Ð»ÑÑ… Ð´Ð¾ ffmpeg (ÑÐºÑ‰Ð¾ Ð² PATH, Ð¿Ñ€Ð¾ÑÑ‚Ð¾ Ð»Ð¸Ñˆ ffmpeg)
ffmpeg:
  path: ffmpeg
>>>>>>> 07e524cff38365d18f4a2145fd917563d99d9eeb
